Added Admin Panel traitment:
nour-nono/pizza-cubed pull request #20
Opened 2024-10-17 02:03 UTC by Fati-Zid

In this PR, I implemented an admin dashboard with the following features:

- [ ]  Profile: Allows authenticated users to update their information.
- [ ] - Categories: Provides full CRUD functionality (Get, Post, Put, Delete) for categories, accessible only by admins.
- [ ] - Menu Items: Enables admins to manage menu items with CRUD operations.

Additionally, I integrated the `zod` npm package for backend request validation to ensure data integrity and security.

2024-10-17 21:01 UTC, nour-nono requested changes

2024-10-17 21:01 UTC, nour-nono commented on src/app/api/profile/route.ts
## first in function PUT:
**country** field is messing, it should be in the **UserInfo** model also.
fields can be empty. code  like `.min(1, 'Street address is too short')` or `.regex(POSTAL_CODE_REGEX, 'Postal code is invalid')` or `.regex(PHONE_NUMBER_REGEX, 'Phone number is invalid')` won't accept that.
i can send fields like **name** or **email** and they are in **User** model so you should update that also.

## second in function GET:
i want to get all the data that user have so you should give me all the data in **User** and **UserInfo**.
because the data is not enough like iam not getting **admin** field

2024-10-17 21:01 UTC, nour-nono commented on src/app/api/auth/[...nextauth]/route.ts
## in line 13: `adapter: MongoDBAdapter(clientPromise)`
add databaseName like this `MongoDBAdapter(clientPromise, {databaseName: process.env.MONGODB_DB})`

you can make the code cleaner instead of rewriting this code twice
```
if (!process.env.MONGODB_URI || !process.env.MONGODB_DB) {
          throw new Error(
            'Missing env variables: "MONGODB_URI" Or "MONGODB_DB"',
          );
        }
        mongoose.connect(process.env.MONGODB_URI, {
          dbName: process.env.MONGODB_DB,
        });
```
also `mongoose.connect` is returning a **promis** so you should wait for it with **await**
you can make it as a function like this:
```
export async function ConnectToDB() {
  if (!process.env.MONGODB_URI || !process.env.MONGODB_DB) {
    throw new Error('Missing env variables: "MONGODB_URI" Or "MONGODB_DB"');
  }

  try {
    await mongoose.connect(process.env.MONGODB_URI, {
      dbName: process.env.MONGODB_DB,
    });
    console.log('Successfully connected to the database');
  } catch (error) {
    console.error('Error connecting to the database', error);
  }
}
```
and use it wherever you want.

2024-10-18 14:02 UTC, Fati-Zid commented on src/app/api/profile/route.ts
for field validation they are optional, if you provide them they should be validated if they are not provided the field validation is escaped

2024-10-18 14:02 UTC, Fati-Zid commented on src/app/api/auth/[...nextauth]/route.ts
refactored to await for database connection

2024-10-22 00:05 UTC, Fati-Zid commented on src/app/models/Order.ts
> +    canceled: { type: Boolean, default: false },
@MamdouhEnahla  I added this field to mark canceled orders. I need it on admin panel

2024-10-22 00:11 UTC, Fati-Zid commented on src/app/api/auth/[...nextauth]/route.ts
I solve this

2024-10-22 10:29 UTC, merged